[project]

[project.urls]
"Documentation" = "https://annhilati.gitbook.com/vpmobil"
"Repository" = "https://github.com/annhilati/vpmobil"
"Bug Tracker" = "https://github.com/annhilati/vpmobil/issues"
"Download" = "https://pypi.org/project/vpmobil/"